### ISSUE TITLE
How Can Use Kali Linux

### ISSUE THREAD

**Issue by Linuxndroid** [mooijtech/go-hydra#1]
Hii Sir Can you Update Your Readme.md File Because How Can use Users This Project Like Kali Linux,Ubuntu, Windows Please Reply My Question
Thanks

**Comment by mooijtech** [comment]
Hello,

If you read the README you would see that this project doesn't work yet.
Please come back later when I've spent more time on this.
By then there will be clear instructions on how to install this (simply opening the binary).

Thank you for question!
